# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jmiCpp <- function(x, y, w) {
    .Call(`_DMI_jmiCpp`, x, y, w)
}

entropyCpp <- function(x, w) {
    .Call(`_DMI_entropyCpp`, x, w)
}

indepCpp <- function(x, y, w) {
    .Call(`_DMI_indepCpp`, x, y, w)
}

balanceCpp <- function(x, y, w) {
    .Call(`_DMI_balanceCpp`, x, y, w)
}

rcpparma_hello_world <- function() {
    .Call(`_DMI_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DMI_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DMI_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DMI_rcpparma_bothproducts`, x)
}

